create DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE  SALARY_TABLE (
EMPLOYEE_ID INT,
NAME VARCHAR(50),
DEPARTMENT_ID  CHAR (60),
SALARY INT);
select*FROM SALARY_TABLE;
INSERT INTO SALARY_TABLE VALUES (101, "Abhishek","D01",62000);
INSERT INTO SALARY_TABLE VALUES(102,"Shubham","D01",58000);
INSERT INTO SALARY_TABLE VALUES(104,"Rohit","D02",640000);
INSERT INTO SALARY_TABLE VALUES(105,"Neha","D03",72000);
INSERT INTO SALARY_TABLE VALUES(106,"Aman","D03",55000);
INSERT INTO SALARY_TABLE VALUES(107,"Ravi","D04",60000);
INSERT INTO SALARY_TABLE VALUES(108,"Sneha","D04",75000);
INSERT INTO SALARY_TABLE VALUES(109,"Kiran","D05",70000);
INSERT INTO SALARY_TABLE VALUES(110,"Tanuja","D05",65000);
select*FROM SALARY_TABLE;

USE EMPLOYEE;
CREATE TABLE DEPARTMENT(
DEPARTMENT_ID VARCHAR(60),
DEPARTMENT_NAME VARCHAR(60),
LOCATION VARCHAR(80)
);
SELECT*FROM DEPARTMENT;
INSERT INTO  DEPARTMENT VALUES("D01","Sales","Mumbai");
INSERT INTO DEPARTMENT VALUES("D02","Marketing","Delhi");
INSERT INTO DEPARTMENT VALUES("D03","Finance","Pune");
INSERT INTO  DEPARTMENT VALUES("D04","HR","Bengaluru");
INSERT INTO DEPARTMENT VALUES("D05","IT","Hyderabad");
SELECT*FROM DEPARTMENT;

USE EMPLOYEE;
CREATE TABLE SALE_TABLE(
SALE_ID INT,
EMP_ID INT,
SALES_AMT INT,
SALES_DATE DATE
);
SELECT*FROM SALE_TABLE;
INSERT INTO SALE_TABLE VALUES(201,101,4500,"2025-01-05");
INSERT INTO SALE_TABLE VALUES (202,102,7800,"2025-01-10");
INSERT INTO SALE_TABLE VALUES (204,104,12000,"2025-01-20");
INSERT INTO SALE_TABLE VALUES(205,105,9800,"2025-02-02");
INSERT INTO SALE_TABLE VALUES(206,106,10500,"2025-02-05");
INSERT INTO SALE_TABLE VALUES(207,107,3200,"2025-02-09");
INSERT INTO SALE_TABLE VALUES(208,108,5100,"2025-02-15");
iNSERT INTO SALE_TABLE VALUES(209,109,3900,"2025-02-20");
iNSERT INTO SALE_TABLE VALUES(210,110,7200,"2025-03-01");
SELECT*FROM SALE_TABLE;

## Retrieve the names of employees who earn more than the average salary of all employees.
SELECT NAME 
FROM SALARY_TABLE
WHERE SALARY >(
SELECT AVG(SALARY)
FROM SALARY_TABLE
);

##Find the employees who belong to the department with the highest average salary.
SELECT NAME 
FROM SALARY_TABLE
WHERE DEPARTMENT_ID=(
SELECT DEPARTMENT_ID
FROM SALARY_TABLE 
GROUP BY  DEPARTMENT_ID
ORDER BY AVG (SALARY) DESC 
LIMIT 1
);
##List all employees who have made at least one sale.
SELECT NAME
FROM SALARY_TABLE
WHERE EMPLOYEE_ID IN(
	SELECT DISTINCT EMPLOYEE_ID
FROM SALE_TABLE
);
##Find the employee with the highest sale amount.
use	EMPLOYEE;
SELECT NAME
 FROM SALARY_TABLE
WHERE EMPLOYEE_ID=(
SELECT EMPLOYEE_ID
 FROM SALES 
 ORDER BY SALES_AMT DESC 
LIMIT 1
);
###Retrieve the names of employees whose salaries are higher than Shubham’s salary.
SELECT name
FROM SALARY_TABLE
WHERE salary > (
    SELECT salary 
    FROM SALARY_TABLE 
    WHERE name = 'Shubham'
);
##Find employees who work in the same department as Abhishek.

SELECT name
FROM SALARY_TABLE
WHERE department_id = (
    SELECT department_id
    FROM SALARY_TABLE
    WHERE name = 'Abhishek'
);
## List departments that have at least one employee earning more than ₹60,000.
SELECT DEPARTMENT_NAME
FROM DEPARTMENT
WHERE DEPARTMENT_ID IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM SALARY_TABLE 
    WHERE SALARY > 60000
);
##Find the department name of the employee who made the highest sale.
SELECT DEPARTMENT_NAME
FROM DEPARTMENT
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID
    FROM SALARY_TABLE
    WHERE EMPLOYEE_ID= (
        SELECT EMPLOYEE_ID
        FROM SALE_TABLE
        ORDER BY SALES_AMT DESC
        LIMIT 1
    )
);
##Retrieve employees who have made sales greater than the average sale amount.
SELECT name
FROM SALARY_TABLE
WHERE EMPLOYEE_ID IN (
    SELECT EMPLOYEE_ID
    FROM SALE_TABLE
    WHERE SALES_AMT > (
        SELECT AVG(SALES_AMT)
        FROM SALE_TABLE
    )
);
##Find the total sales made by employees who earn more than the average salary
SELECT SUM(sale_amount) AS total_sales
FROM sales
WHERE emp_id IN (
    SELECT emp_id
    FROM employee
    WHERE salary > (
        SELECT AVG(salary)
        FROM employee
    )
);

##Find employees who have not made any sales.
SELECT NAME
FROM SALARY_TABLE
WHERE EMPLOYEE_ID NOT IN (
SELECT DISTINCT EMPLOYEE_ID
FROM SALE_TABLE
);
###List departments where the average salary is above ₹55,000.
SELECT DEPARTMENT_NAME 
FROM DEPARTMENT
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM SALARY_TABLE
    GROUP BY DEPARTMENT_ID
    HAVING AVG(SALARY) > 55000
);
## Retrieve the names of employees whose salary is greater than the highest sale amount recorded.
SELECT name
FROM SALARY_TABLE
WHERE SALARY > (
    SELECT MAX(SALES_AMT)
    FROM SALE_TABLE
);

